/* BALMYGARDEN 핵심 메모리 — MEMORY.md 단일 출처에서 동기화.
 * 항목 추가·수정 시 MEMORY.md를 먼저 고치고 이 파일을 맞춘다. */

export type MemoryEntry = { id: string; tag: string; txt: string };

export const MEMORY: MemoryEntry[] = [
  { id: "M-01", tag: "기업", txt: "BALMYGARDEN = BALMYDADDY 전속 음반사. 심포닉/클래시컬 메탈, 다크판타지, 복음 발라드." },
  { id: "M-02", tag: "앱", txt: "영수증 OCR: Next.js 14 / Supabase / Gemini API / Vercel / Resend. 사전 테스팅 단계." },
  { id: "M-03", tag: "게임", txt: "LOD (Lord of Dynasty): React 다크판타지 턴제 RPG 리마스터. 프로토타입 완성." },
  { id: "M-04", tag: "CEO", txt: "김태을 대표. 파라텍 안전보건팀 과장. 모바일 낮 / PC 23시 이후." },
  { id: "M-05", tag: "QA", txt: "전 결과물 QA 95/100 통과 후 CEO 보고. AEGIS → CONDUCTOR 최종 확인." },
  { id: "M-06", tag: "크레딧", txt: "Higgsfield 월 크레딧 = LOD 게임 아트 전용. CEO 승인 전 타 용도 절대 금지." },
  { id: "M-07", tag: "Fugu", txt: "에이전트 배정 시 이유 공개 필수. 블랙박스 금지 (CONDUCTOR 핵심)." },
  { id: "M-08", tag: "배급", txt: "DistroKid 음원 배급. 아티스트: BALMYDADDY, JEDMIR, DUBUREN." },
  { id: "M-09", tag: "스택", txt: "GitHub: balmydaddy/lord-of-dark. CI/CD: Harness.io → Vercel. Obsidian: D:\\obsidian\\obsidian." },
  { id: "M-10", tag: "소스", txt: "모니터링 채택(5): prompt_what, nookitokki, chase.h.ai, whopdwho, linamond.insight(v4.0 신규·AI/리서치 분석). 기존유지: @parky0ngnam, @_business.story, @shoppduddn_, @platformtree_, trenddalkak_ai, keanu_visuals. 거부(6): girsta, thesaar_ai, ainewsdly, adityaa.daily, __3ceo, bestapps_ai (검증불가 수익주장)." },
  { id: "M-11", tag: "학습", txt: "v3.0 탑재: 파인만·오류시뮬·번역기·경로설계·빈틈탐지·곡선파괴 6종." },
  { id: "M-12", tag: "마케팅", txt: "v3.0 탑재: 고객조사·이메일·광고카피·포지셔닝·상세페이지·크리에이터·영상스크립트 7종." },
  { id: "M-13", tag: "콘텐츠", txt: "훅 20개 + How-To·팁·스토리텔링 각 10개 탑재. MUSE/NOVA 우선 활용." },
  { id: "M-14", tag: "안전", txt: "ISO 45001/14001, 중대재해처벌법, 산업안전기사 준비 중. 파라텍 20개 현장." },
  { id: "M-15", tag: "버전", txt: "Dashboard v3.2 (2026.06.27). 신규: MUSIC OS v1.0 + GOSARI 프로젝트 탭 + 예약 탭 + 자동 Notion 저장." },
  { id: "M-16", tag: "12단계", txt: "@platformtree_ 사업 성장 사다리. BG 현황: 음악=2단계(기술판매), 앱/게임=3단계(제품판매)." },
  { id: "M-17", tag: "MUSIC OS", txt: "BALMY MUSIC OS v1.0 파이프라인 12단계. 담당: SAGE→LYRA→MUSE→STROBE→NOVA→REX." },
  { id: "M-18", tag: "GOSARI", txt: "PROJECT GOSARI EP 6트랙. 테마: 시간. 효도송 아님. 장면 우선, 진심 우선." },
  { id: "M-19", tag: "제작규칙", txt: "MUSIC OS 절대 규칙: 가사 먼저 쓰지 않는다. SAGE 없이 LYRA 단독 작성 금지." },
  { id: "M-20", tag: "QG", txt: "Quality Gate 12단계 × 8항목(감정전달력·기억성·독창성·스토리·상업성·가창성·제작성·브랜딩). 전항목 90+ = PASS. FAIL 시 담당 에이전트 개선 루프." },
  { id: "M-21", tag: "v4.0", txt: "MUSIC OS v4.0 = \"AI 크리에이티브 스튜디오\". QG탭→STUDIO탭(채점/리뷰/PM/토론 4서브탭). GOSARI 파이프라인 12→14단계." },
  { id: "M-22", tag: "Creative", txt: "Creative Bible + Style Guide 확정 필수. SAGE+CEO 서명 전 LYRA 작성 불가. MUSIC OS 절대 순서: OS검증→Bible승인→컨셉→세계관→트랙→시나리오→가사→Suno→음원선택→비주얼→MV→발매패키지→마케팅→발매아카이브." },
  { id: "M-23", tag: "Review", txt: "Production Memory = PM-001 형식. 성공 패턴 90점+ 사례만 저장. 다음 트랙 재사용 기준." },
  { id: "M-24", tag: "Conflict", txt: "Creative Conflict: 에이전트 병렬 토론 → CONDUCTOR 결정 → DecisionLog 자동 기록 → CEO Approval Gate (이중 승인)." },
  { id: "M-25", tag: "GOSARI", txt: "GOSARI Creative Bible: 장르=Modern Emotional Trot. North Star=\"눈물을 강요하지 말고, 기억을 깨워라.\" QG 97.25 PASS." },
  { id: "M-26", tag: "GOSARI", txt: "Core Emotion 순서: 공감→미소→회상→먹먹함→감사→희망. 먹먹함=결과, 감사=목적. 필수요소: 손·사진·집·밥·전화·시간·아이·부모·일상." },
  { id: "M-27", tag: "GOSARI", txt: "현재 진행 상태: Creative Bible PASS·Scene Board PASS(97.6). 다음 = STEP 6 Track 1 작사 (LYRA 담당)." },
  { id: "M-28", tag: "GOSARI", txt: "T01 Scene Board 10장면 (06-B 추가). 06-B = 새벽 양육 장면. \"그날도 엄마는 이랬겠구나\" → 가사 직접 서술 금지. 장면으로 전달." },
  { id: "M-29", tag: "LYRA규칙", txt: "T01 작사 규칙: ① Scene 순서 변경 불가 ② 장면 추가·삭제 불가 ③ 06-B 핵심감정 설명형 서술 금지 ④ Required Elements Symbol 해당 Scene 포함 필수 ⑤ Scene 08 이후 대화 가사 금지 ⑥ Cinema Test 통과 후 착수." },
  { id: "M-30", tag: "CinemaTest", txt: "MUSIC OS 신규 규칙. 눈 감고 장면이 보이는가? 3항목 Pass(장면 시각화/감정 설명 없이 전달/소리 꺼도 이야기) → LYRA 착수. Fail → SAGE 재작업." },
  { id: "M-31", tag: "T01QG", txt: "Scene Board v0.2 QG 98.5 PASS+. Commercial Impact 신규 항목. Scene 08 \"상대 목소리 없음\" = 청자가 부모 목소리 상상 → 공감 범위 무한 확장 설계." },
  { id: "M-32", tag: "P-07", txt: "Production Rule P-07: \"Lyrics 작성 전 Producer Blueprint 먼저 완성\". SAGE→CONDUCTOR(Blueprint)→LYRA 순서 절대 규칙. 블루프린트 없이 LYRA 착수 금지." },
  { id: "M-33", tag: "파이프라인", txt: "GOSARI 파이프라인 15단계 확정. STEP 6(시나리오)→STEP 7(Producer Blueprint, CONDUCTOR)→STEP 8(가사, LYRA). 기존 7→14단계 전부 +1 이동." },
  { id: "M-34", tag: "Blueprint", txt: "GOSARI_SONG_BLUEPRINT_T01.md = T01 \"늦게 알았네\" Producer Blueprint. Hook Placement/Silence Design/Dynamic Curve/Symbol Timing/Breath Point/Cinema Test++ 포함. QG 97.6 PASS." },
  { id: "M-35", tag: "설계원칙", txt: "\"Scene 08이 가장 조용한 순간이어야 한다. 감사는 폭발이 아니라 고요함에서 온다.\" Dynamic Curve 최저점=Scene 08(50%). Final Hook=\"엄마… 그냥 전화했어.\" = 전체 가사의 도착점." },
  { id: "M-36", tag: "OS선언", txt: "BALMY MUSIC OS = \"음악 프로덕션 시스템\" (선언 2026-07-01). CEO Vision→Creative Bible→Scene Board→Producer Blueprint→QG→LYRA = 실제 음반사 Pre-production 구조. Production Ready 99.2." },
  { id: "M-37", tag: "P-08", txt: "Emotion Map: Intro=20, Verse1=35, Pre=45, Chorus1=70, Verse2=60, 06-B=85, Chorus2=80, Bridge=90, FinalHook=95, Outro=100. 강도 90+ = 가장 단순한 언어." },
  { id: "M-38", tag: "P-09", txt: "Keyword Density: \"늦게 알았네\"=6회, 손=4회, 아이=5회, 부모=3회, 고사리=1~2회(Final Hook/Outro 전용·이전 절대금지), 밥·집·사진·전화=각 1~2회." },
  { id: "M-39", tag: "P-10", txt: "Hook Protection Rule: 후렴 핵심 단어(\"늦게\", \"알았네\", \"늦게 알았네\")는 Chorus 1 이전 벌스에서 절대 사용 금지. 폭발력 보호 원칙." },
  { id: "M-40", tag: "LYRA순서", txt: "LYRA 작사 순서: 1.Hook→2.Final Hook→3.Bridge→4.Verse1→5.Verse2→6.Intro→7.Outro→8.리듬검토→9.QG. 후렴 먼저 완성 후 벌스 설계. Version 0.1부터 시작." },
  { id: "M-41", tag: "AgentRole", txt: "Agent Role Matrix: SAGE=세계관(가사작성금지), CONDUCTOR=프로듀싱(직접작사금지), LYRA=작사(세계관변경금지), MUSE=Suno(스토리변경금지), NOVA=시장성(감정선변경금지)." },
  { id: "M-42", tag: "P-11", txt: "Rewrite Rule: PASS가 아닌 Freeze가 목표. \"더 고칠 수 있지만 고치지 않기로 결정하는 순간\" = 완성. Freeze=CONDUCTOR 선언+CEO 확정." },
  { id: "M-43", tag: "P-12", txt: "Kill Rule: 3회 Rewrite 후 Still Bad = Archive. 죽일 줄 아는 것도 프로듀싱. Kill=CONDUCTOR 제안+CEO 결정. 파일 보존." },
  { id: "M-44", tag: "P-13", txt: "Time Test: Version 완성 후 24시간 보관 후 재독. 즉시 QG 금지. Rewrite 3회 차는 면제." },
  { id: "M-45", tag: "P-14", txt: "Read Aloud Test: 소리 내서 읽기. 숨/입에붙음/생활어/대화체 4항목 Pass 필수. 1항목 Fail = 해당 문장 재작성." },
  { id: "M-46", tag: "P-15", txt: "Human Test (최우선): \"이 노래 듣고 부모님께 전화하고 싶었는가?\" YES=PASS / NO=Rewrite. 모든 QG보다 우선." },
  { id: "M-47", tag: "G-01", txt: "GOSARI Symbol Reveal: T01 고사리 설명 안 함(1~2회 최대) / T02 의미 개방 / T03+ 삶의 순환 확장. EP 전체가 하나의 은유 완성 구조." },
  { id: "M-48", tag: "v4.1", txt: "MUSIC OS v4.1 = Production Grade 100/100. \"시스템 추가 중단. 작품으로 증명할 차례.\" 다음 = LYRA T01 Version 0.1." },
  { id: "M-49", tag: "문서규칙", txt: "모든 문서(Notion·MD·보고서) 작성 시 오탈자·수치·날짜·에이전트명 검토 후 최종 저장. 초안 ≠ 완성. 검토 완료 후 저장이 원칙. CLAUDE.md 등재 완료." },
  { id: "M-50", tag: "T01Hook", txt: "LYRA T01 Hook v0.1 작성 완료 (2026-07-01). \"늦게 알았네 / 정말 늦게 알았네 / 내 손을 꼭 잡아주던 / 그 마음을 / 늦게 알았네 / 이제야 알았네 / 내 아이 손을 잡고서야 / 당신을 알았네\". QG 보류 — P-13/P-14/P-15 미적용. CONDUCTOR 지시: v0.2에서 장면화 강화." },
  { id: "M-51", tag: "HookMemory", txt: "Hook Memory Test 신규 체크리스트. 3항목: ①한 문장이 선명하게 남는가 ②청자가 자기 이야기로 가져가는가 ③그 문장이 행동을 유발하는가. 핵심 원칙: \"이 문장은 슬프다고 말하는가, 아니면 누군가의 기억을 깨우는가?\" v0.1 판정=🟡조건부보류." },
  { id: "M-52", tag: "P-16", txt: "Memory Resonance Test (MRT) — 구 Memory Trigger Test. 시간 레이어별 여운 평가: 30초=첫 떠오름/5분=지속 잔상/다음 날=재생 여부. \"좋은 가사였다\"=FAIL. 구체적 장면·목소리·순간=PASS. 가사 품질이 아닌 기억 여운 평가." },
  { id: "M-53", tag: "P-17", txt: "Hook Layer Test 신규 제정. 한 후렴이 여러 청자층에 다른 기억을 유발하는가. 20대=부모님 생각/30대=아이 생각/부모 잃은 사람=그리움/아이 없는 사람=어린 시절. 다른 기억 유발=PASS. 보편적 개인화 설계 기준." },
  { id: "M-54", tag: "G-02", txt: "Empty Space Rule (GOSARI 전용). 감정 일부를 비워둔다. 설명하지 않은 공간에 청자가 자기 이유를 채운다. 예: \"엄마... 그냥 전화했어.\" — 이유 설명 없음=여백=청자 자기화. 완성도가 아닌 여백이 공감을 만든다." },
  { id: "M-55", tag: "철학", txt: "CONDUCTOR 선언 (2026-07-01): \"좋은 가사를 만든다\" → \"사람의 기억이 머무를 공간을 만든다\". 평가 기준 전환: 가사 품질 → 청자 기억 활성화. GOSARI EP 전체 + 이후 모든 트랙 적용." },
  { id: "M-56", tag: "G-03", txt: "Truth Filter (GOSARI 전용). \"이 문장은 실제로 사람이 할 법한 말인가?\" \"당신의 사랑을 이제야 이해했습니다\"=❌ / \"엄마... 그냥 전화했어\"=✅. Creative Bible 생활어 70% 원칙과 직결. 입 밖에 내 봤을 때 어색하면 가사도 어색하다." },
  { id: "M-57", tag: "P-18", txt: "One Breath Test. \"후렴의 핵심은 한 번의 숨으로 끝까지 말할 수 있는가?\" 호흡이 끊기면 감정도 끊긴다. P-14 Read Aloud Test의 구체화. 후렴 완성 후 실제 한 숨 발화 테스트 필수." },
  { id: "M-58", tag: "시스템", txt: "Rule Adoption Gate 확정. 신규 Rule 추가 전 필수 질문: \"이 규칙은 '늦게 알았네'를 더 좋은 노래로 만드는가, 아니면 시스템만 더 복잡하게 만드는가?\" YES=채택 / NO=보류. v4.1 이후 시스템 추가 동결." },
  { id: "M-59", tag: "T01테스트", txt: "P-13 PASS (72시간 경과 2026-07-04). P-14 조건부 PASS (숨/입/생활어 PASS, 대화체 약함). P-15 조건부 NO (\"그 마음을\"/\"당신을 알았네\" 감정 선언, 장면 없음, 행동 유발 실패). → P-11 Rewrite." },
  { id: "M-60", tag: "HookV02", txt: "Hook v0.2 (2026-07-04). 변경: \"내 손을 꼭 잡아주던/그 마음을\" → \"꼭 쥔 이 손이/이렇게 작은 걸\" / \"당신을 알았네\" → \"당신이 보였네\". 채택 장면: 아이가 내 손을 꽉 잡는 순간. G-02(여백)/G-03(진실) 적용. P-10 유지." },
  { id: "M-61", tag: "콘텐츠기준", txt: "학습 콘텐츠 등재 기준 확정. 검증 불가 수익·성과 주장 소스 등재 금지. 구조가 유효하면 구조만 일반화, 수치 주장 폐기. 채택4(prompt_what/nookitokki/whopdwho/parky0ngnam), 부분2(chase.h.ai/adityaa), 거부6." },
  { id: "M-62", tag: "모델라우팅", txt: "비용 60-30-10 확정. Haiku 60%(분류·요약·단순판단) / Sonnet 30%(실무생성) / 상위 10%(CONDUCTOR·AEGIS·NOVA). 초기 8:2 시작 후 조정. 병렬=독립작업만. 긴 세션: 목표·결정·미완료·다음액션 200자 압축 인계." },
  { id: "M-63", tag: "AEGIS보강", txt: "검증 세션 분리 원칙. 결과물 검증은 생성 세션과 분리된 새 컨텍스트(서브에이전트/새 대화)에서 배경 없이 수행. 자기 검토는 게이트 통과 불인정. CONTRACT 포맷: 목표·제약·포맷·실패조건 4항목 미기재 시 착수 금지. 완료 조건 수치화 필수." },
  { id: "M-64", tag: "프롬프트", txt: "신규 카테고리 확정. 페이블5 운영규칙 9종(과잉지시제거/난이도최상단/의도먼저/행동우선/결론우선/증거기반보고/검증세션분리/effort노브/추론재현지시금지). 사업전략 7종(parky0ngnam). 개발도구 카탈로그(whopdwho). 비즈니스자동화 파이프라인 템플릿." },
  { id: "M-65", tag: "노션구조", txt: "CLAUDE.md = [A]에이전시시스템 / [B]PROJECT GOSARI 두 블록으로 구분. 노션 \"BALMYGARDEN—미결사항\" 페이지 생성(ID: 393987a2-5d61-8105-8168-d54da40a5d77). 매 세션 종료 시 최신화 필수. Agency HQ 하위에 위치." },
  { id: "M-66", tag: "v4.0", txt: "Agency OS v4.0 (2026-07-06). 참조: TradingAgents 논문(UCLA/MIT). 핵심 설계: 병렬 전문가 → 찬반 토론 → 단일 최종 결정. 신규 4개 프로토콜: PRP(Parallel Research Protocol, 전문 에이전트 병렬 분석), CDG(Creative Debate Gate, 3단계 FOR/AGAINST 토론), FAP(Final Authority Protocol, CONDUCTOR 결정 범위 vs CEO 필수 매트릭스), RFS(Risk Flag System, 법적/품질/일정/평판/기술 5항목 체크리스트). 에이전트 테이블에 v4.0 레이어 컬럼 추가. linamond.insight SCOUT 소스 신규 채택(AI/리서치 고밀도 분석 콘텐츠)." },
  { id: "M-67", tag: "PMO", txt: "노션 미결사항 페이지 PMO 구조 전환 (2026-07-06). 7개 카테고리: CEO요청(C)/AI발견(D)/TechDebt/QualityIssues(Q)/CEO결정(DR)/Blockers(B)/FutureIdeas(F). Rule PM-01: 작업은 하나의 카테고리에만 속함. Priority: P0/P1/P2/P3/Icebox. Status: Draft/Ready/In Progress/Waiting/Blocked/Review/Approved/Done/Archived. 최상단 Executive Summary (4개 프로젝트 현황 30초 파악)." },
  { id: "M-68", tag: "세션로그", txt: "Claude=Build / ChatGPT=Review 역할 구분 정책 확정 (2026-07-06). 세션 로그 & Rule Adoption Log 전용 노션 페이지 신설 (ID: 395987a2-5d61-8104-872c-e1c21fffe329). 매 세션 종료 시 Claude Update + ChatGPT Review 형식으로 추가. Rule 채택 시 제안자·날짜 기록 필수." },
  { id: "M-69", tag: "v0.3통합", txt: "BALMYGARDEN 운영 지침 v0.3 (ChatGPT 생성) → v4.0 빌드업 반영 (2026-07-09). 신규 채택: T1/T2/T3 태스크 등급 판정(즉답·실무·중대, T3만 서두 고지), 중단·에스컬레이션 규칙 4조건(2회미달/비가역조작/근거없는사실주장/지침충돌), 원인 진단 원칙(증상 아닌 원인 먼저 특정), 오류 처리 규칙(축소·과잉사과 금지, 원인+수정만), 최적화 원칙(항목추가 시 기존 삭제 검토). 충돌 항목: 어조(v0.3 편안한대화체 < v4.0 업무보고형식 → v4.0 유지). 중복 스킵: 결론우선·행동우선·증거기반·Fugu원칙." },
  { id: "M-70", tag: "HookFreeze", txt: "Hook v0.2 공식 Freeze 확정 (2026-07-09). P-16 MRT 3인(CEO+친구1솔로+친구2아이둘) 전원 PASS. 친구1(솔로): 작은손 시각화→누나 연상(P-17 솔로레이어 작동). 친구2(아이둘): 내아이손→행동유발(\"오늘 잘하자\")→자발재생(\"아참 그거\"). 전원 \"좋은가사였다\" 응답 없음. CONDUCTOR 선언: \"G-02 여백 작동 확인. 더 고칠 수 있지만 고치지 않기로 결정.\" 다음 = Bridge → Verse 1 → Verse 2 → Intro → Outro → QG → Suno(M-40 순서)." },
  { id: "M-71", tag: "HookFreeze2", txt: "Hook v0.3 공식 Freeze 확정 (2026-07-10). P-13/P-14(조건부)/P-15/P-16 전항목 PASS. 핵심: \"손의 체온\" → 기억 검색 키. P-16 동시 현상: 자녀 있는 사람 = 자녀+부모 손 동시 활성화. Bridge v0.1 착수 (Scene 07 / 사진 / \"그냥 보고 싶다\"). P-13 타이머: 2026-07-10~11." },
  { id: "M-72", tag: "비주얼참고", txt: "fieldby 레퍼런스 보드 프롬프트 가이드 (2026-07-31 확인). ChatGPT/Gemini + 기준 사진 1장으로 설정 시트 생성. 활용 범위: ①LOD 게임 아트 — Higgsfield 생성 전 크리처·캐릭터·장소·포즈 보드로 아트 일관성 확보 (즉시 적용 가능, 비용 없음) ②GOSARI MV — STROBE 단계 투입 시 캐릭터·샷(12컷 콘티)·장소 보드 활용 ③BALMYDADDY SNS 마케팅 — 캐릭터 보드(아티스트 이미지 일관성)+샷 보드(릴스 콘티) ④앱 트랙 — 현 테스팅 단계 해당 없음." },
  { id: "M-73", tag: "SCOUT자동화", txt: "네이버 검색 API 뉴스 브리핑 파이프라인 도입 (2026-07-31, prompt_what 영상 5편 판독). `/api/naver-news` 신설. GET=키워드·프리셋 수집 / POST=수집 후 Notion 자동 저장(save_log, source=SCOUT). 인증 2경로 자동 선택: 개발자센터(NAVER_CLIENT_ID/SECRET) 또는 NCP API HUB(NCP_APIGW_API_KEY_ID/KEY). SCOUT 프리셋 4종: music/app/game/safety(중대재해처벌법·ISO 45001 — CEO 본업 직결). 제목 중복제거+HTML 태그 정리 포함. **미검증: API 키 미발급으로 실호출 테스트 불가.**" },
  { id: "M-74", tag: "트레이딩탭", txt: "대시보드 트레이딩 탭 신설 (2026-07-31). CEO 제공 TradingTab.jsx를 .tsx 재작성 후 통합. 수정 사항: ①localhost 하드코딩 → `/api/trading` 서버 프록시 (배포본 HTTPS mixed content 차단 회피) ②테마 정합 (#0d1629 카드/#1e293b 테두리) ③모바일 2열 대응 ④document.hidden 폴링 중단 ⑤탭 열릴 때만 마운트 ⑥RSI는 signal.rsi 우선·정규식은 폴백 ⑦오프라인 시 원인·조치 표시. 배포본 연결 조건: 트레이딩 서버 터널 노출 + TRADING_SERVER_URL 환경변수. 목 서버로 LIVE 렌더 검증 완료." },
  { id: "M-75", tag: "Bridge현존", txt: "Bridge v0.1 P-13 PASS 확정 (2026-08-01, 22일 경과 재독). 신규 발견 3건: ①구도 전환 — Hook은 손을 잡음(상호), Bridge는 나를 안고 있음(받음) → 감사의 전제 ②인물 범위 확장 — 직계 2세대(부모·자녀)에서 확장 친족 다세대(조부모·삼촌·이모)로. 가사는 단수 \"당신\", 기억은 복수 → G-02 여백 작동 ③**현존 현상** — 회상이 아니라 그 장면 안에 있음. CONDUCTOR 미션 \"기억이 머무를 공간\" 1차 증거. 강도 판단 정정: 아련함+현존감 공존 = 강도 미달이 아니라 시간이 접히는 상태. M-35 \"감사는 폭발이 아니라 고요함에서 온다\"에 부합." },
];
